### ISSUE TITLE
Express server

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/price-fetch-server#1]
## Setup Express Server to Request token prices from external APIs
We will either use Coin Gecko or Coin Market cap API to get the prices of each token at a given time. 

## Background
- We need the normalised USDT value. This is needed for two reasons 1) so that we can communicate the total value lock across all tokens. 2) Data Farming needs information on which datasets have generated the most value from downloads. For comparison, the value needs to be expressed in a common currency 
- Subgraph is not able to request this information from the API directly as it cannot do HTTP request
- We can't use an oracle because we use private networks and test networks etc. where the is no oracle available. It would also add unnecessary costs to each request. 
- The Subgraph is able to fetch IPFS files. So the request to this server will be done as if it is requesting a file from IPFS. 

## Tasks

- [x] Setup Express server
- [x] Create route for recieeving the request. The ENdpoint will be the following:
`GET  /ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/TOKEN_SYMBOL/TIMESTAMP`
- [x] Request price information from external API
- [x] Respond with price information
- [x] Add a caching mechanism as well to store the last 10-15 minutes' values. This will save us from sending too many requests to the API.
